experiment_directory: /gpfs/commons/instruments/pyseq/SND10310/20220801_4color/
output_directory: /gpfs/commons/groups/nygcfaculty/PySeq
resources:
  dask_worker:
    manager: SLURM
    # or specify in .config/dask/jobqueue.yaml
    #queue: pe2
    #cores: 2
    memory: 32G
    log_directory: dask_logs
markers:
  # cycle:
  #   channel1: marker1
  #   channel2: marker2
  1:
    610: TDP43
    687: CD34
    740: yH2AX
  2:
    610: CD68
    740: pTDP43
  3:
    610: IBA1
    687: GFAP
    740: NeuN

#segmentation:
#  marker: LMN1b_5
unmix:
  max_iter: 100              # Max iterations to optimize unmixing
gpu_spec:
  partition: gpu
  gres: gpu:tesla:1
reference:
  seurat: /gpfs/commons/groups/compbio/projects/rf_scrna_refs/mouse_spinalcord_seurat_object_subset.rds
  typecol: cell_type

